language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "r16u+cNCMrIbL9BdvdjvYzZYwcAzOfBvLSlh1J/FFRGhuoBm1nrr/Vh4YKzQZHw3HJg0Qxl6xSHR9k305+//0xZFiYP7OREIx5mD9Og0ydm5M+IHXtcLTGFiXLs4Mm6cpbrbrzCCi2dgmYDkhwoaU+M2nes3sLIvXamC7h5aysM="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
